/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/add_climb": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Add Climb */
		post: operations["add_climb_add_climb_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/all_climbs": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** All Climbs */
		get: operations["all_climbs_all_climbs_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** Climb */
		Climb: {
			/** Id */
			id?: number | null;
			/**
			 * Date
			 * Format: date
			 */
			date: string;
			/** Media Url */
			media_url: string;
			/** Is Video */
			is_video: boolean;
			grade: components["schemas"]["Grade"];
			grade_opinion: components["schemas"]["GradeOpinion"];
			color: components["schemas"]["Color"] | null;
			/** Styles */
			styles: components["schemas"]["Style"][];
			/** Complete */
			complete: boolean;
			/** Flash */
			flash: boolean;
			/** Outdoor */
			outdoor: boolean;
			/** Favorite */
			favorite: boolean;
		};
		/**
		 * Color
		 * @enum {string}
		 */
		Color: Color;
		/**
		 * Grade
		 * @enum {string}
		 */
		Grade: Grade;
		/**
		 * GradeOpinion
		 * @enum {string}
		 */
		GradeOpinion: GradeOpinion;
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components["schemas"]["ValidationError"][];
		};
		/**
		 * Style
		 * @enum {string}
		 */
		Style: Style;
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	add_climb_add_climb_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["Climb"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	all_climbs_all_climbs_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
		};
	};
}
export enum Color {
	red = "red",
	orange = "orange",
	yellow = "yellow",
	green = "green",
	teal = "teal",
	blue = "blue",
	purple = "purple",
	pink = "pink",
	black = "black",
	white = "white",
}
export enum Grade {
	V_ = "V?",
	VB = "VB",
	V0 = "V0",
	V1 = "V1",
	V2 = "V2",
	V3 = "V3",
	V4 = "V4",
	V5 = "V5",
	V6 = "V6",
	V7 = "V7",
	V8 = "V8",
	V9 = "V9",
	V10 = "V10",
}
export enum GradeOpinion {
	soft = "soft",
	normal = "normal",
	hard = "hard",
}
export enum Style {
	jugs = "jugs",
	crimps = "crimps",
	slopers = "slopers",
	pockets = "pockets",
	pinches = "pinches",
	blocks = "blocks",
	sidePulls = "side pulls",
	slab = "slab",
	tension = "tension",
	heelHook = "heel hook",
	toeHook = "toe hook",
	dyno = "dyno",
	coordination = "coordination",
	compression = "compression",
	mantle = "mantle",
	kneeBar = "knee bar",
	batHang = "bat hang",
}
